dist: trusty
sudo: required
language: cpp
compiler:
- gcc
- clang

os:
- linux
- osx

osx_image: xcode8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - gcc-5
    - libxrandr-dev
    - libxinerama-dev
    - libxcursor-dev

env:
  global:
  - PATH=$HOME/miniconda/bin:$PATH
  - MACOSX_DEPLOYMENT_TARGET=10.7

  matrix:
  - python=2.7 CONDA_PY=27
  - python=3.6 CONDY_PY=36

matrix:
  exclude:
  - os: linux
    compiler: clang
  - os: osx
    compiler: gcc

cache:
  apt: true

notifications:
  email: false

before_install:
- PY_VER=${CONDA_PY:0:1} devtools/travis/setup_miniconda.sh
install:
- if [ "$CXX" = "g++" ]; then export CXX="/usr/lib/ccache/g++-5" CC="/usr/lib/ccache/gcc-5"; fi
- conda build conda.recipe
- source activate test-environment
- conda install --use-local readdyviewer

script:
- python tests/test.py