dist: trusty
sudo: required
language: cpp
compiler:
- gcc
- clang

os:
- linux
- osx

osx_image: xcode8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - gcc-5
    - libxrandr-dev
    - libxinerama-dev
    - libxcursor-dev

env:
  global:
  - PATH=$HOME/_cmake/bin:$HOME/miniconda/bin:$PATH
  - MACOSX_DEPLOYMENT_TARGET=10.7
  - secure: xGI6QxgkdBYC2wVQziEOaYrADG4eYm6l6aQThQmd3PbZB7g5zSvcltNzPj7DbjvWSYqd5D8zpVtvVkV3FulB3dNEVEgJSI8gRQ7nEDXw6qAz55zcAKSWNjJFIVnhbMuF62rVKnecAueLtqAtfoy3ySJyvvC3g9apTZc6b7AnHd75QsuE0KMeyZ0EoD4F7xACtRoI+DqLyj5aoPwJECxGH32nr0MDoyxbWcklvFQ0Sb6x7ele4J1ewsbSsT810xdrSUBhoOyZCLXFoNh41CWULJ9wcUD9rGqnQ6XWxKYhfFruUbF0xwPduSA7lr2NnYjE0Yo3Sk5oTCRRWFpQVS0P4uP5WmxrIVtwiWyb6+I9eF84hR0DxsVdBev7/uHeRNtSmXCGZ/I14w+Ig/52y4jdWPPJLLwds2/xnKoz8LVDhR47I9JAA0DBVcYQSDfCMGOLagnlf+n/KzcRHdnCueUKONZ0uHIFwFkSiJEOOUbK4mFlwXuft8+xaFqRsMwSAPto/tNWUDoCz1RnokPltdkTHM94XZYig8j75Nu5GLBkF+E+zqLWbSxSEwbgV6pBjWe1UjKt9SgMfye2tqGvaAQw00SUQMkHE/g6rpphMQ3ZjA+fExvqvkTxHhqG1Q3lqppCv4D8DOuEXX1/1xrS1oGRI6K/FrQfuks0xID7MO+Oxz0=

  matrix:
  - python=2.7 CONDA_PY=27
  - python=3.5 CONDY_PY=35

matrix:
  exclude:
  - os: linux
    compiler: clang
  - os: osx
    compiler: gcc

cache:
  apt: true

notifications:
  email: false

before_install:
- devtools/travis/setup_miniconda.sh
install:
- if [ "$CXX" = "g++" ]; then export CXX="/usr/lib/ccache/g++-5" CC="/usr/lib/ccache/gcc-5"; fi
- conda build conda.recipe
- source activate test-environment
- conda install --use-local readdyviewer

script:
- python tests/test.py