package:
  name: readdyviewer
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'dev') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  script_env:
    - CC
    - CXX

source:
  path: ../

requirements:
  host:
    - python
    - setuptools
    - numpy

  build:
    - python
    - setuptools

  run:
    - python
    - numpy

test:
  imports:
    - readdyviewer

about:
  summary: The readdy viewer.
  license_file: LICENSE